import { useState } from 'react';

export default function FlightSearchPage() {
  const [form, setForm] = useState({ originLocationCode: '', destinationLocationCode: '', departureDate: '', returnDate: '', adults: 1, travelClass: 'ECONOMY' });
  const [state, setState] = useState({ loading: false, error: '', flights: [], updated: null });
  const search = async (event) => { event.preventDefault(); setState({ loading: true, error: '', flights: [], updated: null }); try { const params = new URLSearchParams(Object.entries(form).filter(([, value]) => value !== '').map(([key, value]) => [key, String(value)])); const res = await fetch(`/api/flight-search?${params}`); const data = await res.json(); if (!res.ok || !data.available) throw new Error(data.error || 'Live flight shopping is temporarily unavailable.'); setState({ loading: false, error: '', flights: data.flights || [], updated: data.lastUpdated }); } catch (error) { setState({ loading: false, error: error.message, flights: [], updated: null }); } };
  const field = (label, key, type = 'text', extra = {}) => <label className="text-xs text-white/60">{label}<input required={key !== 'returnDate'} type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: type === 'text' ? e.target.value.toUpperCase() : e.target.value })} {...extra} className="mt-1 w-full rounded-xl bg-black/30 border border-white/10 px-3 py-3 text-white" /></label>;
  return <section className="min-h-screen bg-[#0c0c0c] pt-32 pb-20 px-4 sm:px-8 text-white"><div className="max-w-6xl mx-auto space-y-8"><header><span className="text-xs font-mono text-brand-gold uppercase tracking-[.25em]">Live provider search</span><h1 className="font-serif text-4xl sm:text-6xl mt-2">Find flights</h1><p className="text-white/60 mt-3 max-w-xl">Live offers are supplied by the configured provider. Horizon does not manufacture airline availability or fares.</p></header><form onSubmit={search} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 rounded-3xl bg-white/5 border border-white/10 p-4">{field('Origin IATA code', 'originLocationCode', 'text', { maxLength: 3, placeholder: 'BOM' })}{field('Destination IATA code', 'destinationLocationCode', 'text', { maxLength: 3, placeholder: 'LHR' })}{field('Departure', 'departureDate', 'date')}{field('Return (optional)', 'returnDate', 'date')}{field('Passengers', 'adults', 'number', { min: 1, max: 9 })}<label className="text-xs text-white/60">Cabin<select value={form.travelClass} onChange={(e) => setForm({ ...form, travelClass: e.target.value })} className="mt-1 w-full rounded-xl bg-black/30 border border-white/10 px-3 py-3 text-white"><option>ECONOMY</option><option>PREMIUM_ECONOMY</option><option>BUSINESS</option><option>FIRST</option></select></label><button disabled={state.loading} className="rounded-xl bg-brand-gold px-4 py-3 text-xs font-bold uppercase tracking-wider text-black disabled:opacity-50">{state.loading ? 'Searching…' : 'Search flights'}</button></form>{state.error && <div className="rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100">{state.error}</div>}{state.updated && <p className="text-xs font-mono text-white/45">Amadeus · checked {new Date(state.updated).toLocaleTimeString()}</p>}<div className="space-y-3">{state.flights.map((flight) => <article key={flight.id} className="rounded-2xl border border-white/10 bg-[#121214] p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="text-xs text-brand-gold">{flight.airlineCode} {flight.flightNumber}</p><h2 className="font-serif text-xl mt-1">{flight.origin} → {flight.destination}</h2><p className="mt-1 text-sm text-white/60">{flight.departureTime} · {flight.duration} · {flight.stops === 0 ? 'Non-stop' : `${flight.stops} stop(s)`}</p></div><strong>{flight.price ? `${flight.currency || ''} ${flight.price}` : 'Price unavailable'}</strong></article>)}</div>{!state.loading && !state.error && state.flights.length === 0 && <div className="rounded-3xl border border-white/10 bg-[#121214] p-10 text-center text-white/55">Search with airport codes and dates to see live provider offers.</div>}</div></section>;
}
